"""remove another name field

Revision ID: e2721ced24f6
Revises: 5c513e2189b1
Create Date: 2024-04-10 15:43:19.032617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2721ced24f6'
down_revision = '5c513e2189b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_model', schema=None) as batch_op:
        batch_op.drop_column('another_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('another_name', mysql.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
